#version: '3.8'
#services:
#  postgres-db:
#    container_name: social_db
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_USER: socialdb
#      POSTGRES_PASSWORD: socialdb12'
#      POSTGRES_DB: socialdb
#    ports:
#      - '5432:5432'

#version: '3.8'
services:
  postgres-db:
    container_name: social-db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: socialdb
      POSTGRES_USER: socialdb
      POSTGRES_PASSWORD: socialdb12
    ports:
      - "5433:5432" # Optional: Map container port to host port for direct access
volumes:
  postgresql_data:
    driver: local
